version: '3'

services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    networks:
      - monitoring-net
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-net

networks:
  monitoring-net:
